### ISSUE TITLE
KeyError: 'refid'

### ISSUE THREAD

**Issue by vrtulka23** [mike42/doxyphp2sphinx#4]
Hi I wanted to view my PHP documentation in Sphinx and I followed your article https://mike42.me/blog/2018-06-how-to-create-effective-php-project-documentation-with-read-the-docs . 
Until now everything went smooth, but I came across this error, do you know what is going on?

$ /usr/local/bin/doxyphp2sphinx -v OCA::vdpptasks
Processing namespace OCA::vdpptasks
  refid is namespace_o_c_a_1_1vdpptasks
  Opening xml/namespace_o_c_a_1_1vdpptasks.xml
  Page title will be 'API documentation'
  Page path will be  './api.rst'
  Desc is ... '
    '
Processing namespace OCA::vdpptasks::Controller
  refid is namespace_o_c_a_1_1vdpptasks_1_1_controller
  Opening xml/namespace_o_c_a_1_1vdpptasks_1_1_controller.xml
  Page title will be 'Controller namespace'
  Page path will be  './api/_controller.rst'
  Desc is ... '
    '
Processing class OCA::vdpptasks::Controller::DocuController
  refid is class_o_c_a_1_1vdpptasks_1_1_controller_1_1_docu_controller
  Class title will be 'DocuController'
  Class path will be  './api/controller/docucontroller.rst'
Traceback (most recent call last):
  File "/usr/local/bin/doxyphp2sphinx", line 8, in <module>
    sys.exit(Cli.run())
  File "/usr/local/lib/python3.8/site-packages/doxyphp2sphinx/cli.py", line 28, in run
    generator.render_namespace_by_name(tree, root_namespace)
  File "/usr/local/lib/python3.8/site-packages/doxyphp2sphinx/rstgenerator.py", line 29, in render_namespace_by_name
    self.render_namespace_by_ref_id(child.attrib['refid'], this_namespace_name)
  File "/usr/local/lib/python3.8/site-packages/doxyphp2sphinx/rstgenerator.py", line 79, in render_namespace_by_ref_id
    self.render_namespace_by_ref_id(ns_id, ns_name)
  File "/usr/local/lib/python3.8/site-packages/doxyphp2sphinx/rstgenerator.py", line 74, in render_namespace_by_ref_id
    self.render_class_by_ref_id(cl_id, cl_name)
  File "/usr/local/lib/python3.8/site-packages/doxyphp2sphinx/rstgenerator.py", line 343, in render_class_by_ref_id
    class_rst = self.class_xml_to_rst(compounddef, title)
  File "/usr/local/lib/python3.8/site-packages/doxyphp2sphinx/rstgenerator.py", line 124, in class_xml_to_rst
    baserefid = base_class.attrib['refid']
KeyError: 'refid'

**Comment by cobhimself** [comment]
+1. I'm seeing this as well.

**Comment by cobhimself** [comment]
Seems https://github.com/silverfoxy/doxyphp2sphinx might have a fix for this.

**Comment by hxtree** [comment]
+1 happening here https://github.com/ouxsoft/LivingMarkup . Will have to comment out the EXCLUDE_SYMBOLS to see.
